post comment using pat

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -24,15 +24,9 @@ on:
           - macos-13
           - macos-14
         default: ubuntu-latest
-#  pull_request:
-#    branches:
-#      - main
-  pull_request_target:
-    types: [opened, synchronize, reopened] # Trigger when a PR is opened, updated, or reopened
-
-
-
-permissions: write-all
+  pull_request:
+    branches:
+      - main
 
 jobs:
   build:
@@ -57,8 +51,6 @@ jobs:
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v5
-        with:
-          add-job-summary-as-pr-comment: 'always' # Valid values are 'never' (default), 'always', and 'on-failure'
 
       - name: Cache Gradle dependencies
         uses: actions/cache@v5
@@ -91,12 +83,26 @@ jobs:
         run: pip install -r docs/requirements.txt
 
       - name: Build project (without tests)
+        id: build_project
         run: |
           echo "🔨 Building project..."
           ./gradlew clean || { echo "❌ Clean failed"; exit 1; }
-          ./gradlew assemble || { echo "❌ Assemble failed"; exit 1; }
+          ./gradlew assemble --scan || { echo "❌ Assemble failed"; exit 1; }
           echo "✅ Project built successfully"
         shell: bash
+
+      - name: Add Gradle Scan as PR Comment
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{secrets.PR_COMMENT_TOKEN}}
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: '[Gradle Build Scan](${{steps.build_project.outputs.build-scan-url}})'
+            })
+
 
       - name: Verify Dokka output
         run: |
@@ -172,11 +178,6 @@ jobs:
 
   test:
     runs-on: ${{ matrix.os }}
-    permissions: write-all
-#      contents: read
-#      pull-requests: write
-#      statuses: write
-#      issues: write
     strategy:
       matrix:
         os: ${{ inputs.os && fromJSON(format('["{0}"]', inputs.os)) || fromJSON('["ubuntu-latest","macos-latest"]') }}
@@ -203,8 +204,6 @@ jobs:
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v5
-        with:
-          add-job-summary-as-pr-comment: 'always' # Valid values are 'never' (default), 'always', and 'on-failure'
 
       - name: Cache Gradle dependencies
         uses: actions/cache@v5
@@ -299,8 +298,6 @@ jobs:
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v5
-        with:
-          add-job-summary-as-pr-comment: 'always' # Valid values are 'never' (default), 'always', and 'on-failure'
 
       - name: Cache Gradle dependencies
         uses: actions/cache@v5
@@ -353,8 +350,6 @@ jobs:
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v5
-        with:
-          add-job-summary-as-pr-comment: 'always' # Valid values are 'never' (default), 'always', and 'on-failure'
 
       - name: Cache Gradle dependencies
         uses: actions/cache@v5
@@ -401,8 +396,6 @@ jobs:
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v5
-        with:
-          add-job-summary-as-pr-comment: 'always' # Valid values are 'never' (default), 'always', and 'on-failure'
 
       - name: Cache Gradle dependencies
         uses: actions/cache@v5
