fix: Fix build-and-test.yml script java-api library in dokka generation. (AIRBNB)
Github-Change-Id: 1020052
GitOrigin-RevId: b2bf667e9de0d6b5badab1b3e7eb9d641a049b76

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -94,7 +94,7 @@ jobs:
           cd ..
 
           echo "🔨 Building Dokka documentation..."
-          ./gradlew :core:tenant:tenant-api:dokkaGenerate :core:service:dokkaGenerate :core:x:javaapi:x-javaapi-api:dokkaGenerate || { echo "❌ Dokka failed"; exit 1; }
+          ./gradlew :core:tenant:tenant-api:dokkaGenerate :core:service:dokkaGenerate :core:x:javaapi:javaapi-api:dokkaGenerate || { echo "❌ Dokka failed"; exit 1; }
 
           echo "📖 Verifying Dokka documentation output..."
 
